https://blog.paperspace.com/intro-to-optimization-momentum-rmsprop-adam/

In [0]:
import keras

In [0]:
#model.summary()

In [0]:
from keras.datasets import mnist
from keras.utils import to_categorical

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [20]:
train_images.shape

(60000, 28, 28)

In [21]:
train_images[0].shape



(28, 28)

In [0]:
train_images[0]

In [23]:
train_labels[0]

5

In [0]:
train_images = train_images.reshape((60000, 28, 28, 1))

In [25]:
train_images.shape

(60000, 28, 28, 1)

In [0]:
test_labels[0]

In [0]:
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28, 28, 1))
test_images = test_images.astype('float32') / 255

In [0]:
train_images[0]


In [28]:
train_labels[0]

5

In [0]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [31]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [32]:
print train_labels.shape

(60000, 10)


In [0]:
from keras import layers
from keras import models

model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(16, (5,5), activation = "relu"))
model.add(layers.MaxPooling2D((2, 2)))



In [0]:
model.add(layers.Flatten())

model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [35]:

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=50, batch_size=64)

Epoch 1/50
60000/60000 [==============================] - 4s 73us/step - loss: 0.2177 - acc: 0.9344
Epoch 2/50
60000/60000 [==============================] - 4s 69us/step - loss: 0.0688 - acc: 0.9790
Epoch 3/50
60000/60000 [==============================] - 4s 69us/step - loss: 0.0493 - acc: 0.9845
Epoch 4/50
60000/60000 [==============================] - 4s 68us/step - loss: 0.0377 - acc: 0.9881
Epoch 5/50
60000/60000 [==============================] - 4s 70us/step - loss: 0.0309 - acc: 0.9902
Epoch 6/50
60000/60000 [==============================] - 4s 68us/step - loss: 0.0264 - acc: 0.9920
Epoch 7/50
60000/60000 [==============================] - 4s 68us/step - loss: 0.0223 - acc: 0.9931
Epoch 8/50
60000/60000 [==============================] - 4s 68us/step - loss: 0.0189 - acc: 0.9943
Epoch 9/50
60000/60000 [==============================] - 4s 68us/step - loss: 0.0171 - acc: 0.9949
Epoch 10/50
60000/60000 [==============================] - 4s 68us/step - loss: 0.0150 - acc: 0.9955

In [36]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 55us/step


In [0]:
test_images[0].shape

In [37]:
test_acc


0.9891

In [0]:
model.layers

In [0]:
train_images[0].shape

In [0]:
type(train_images)

In [0]:
test_data = train_images[10].reshape(1,28,28,1)

In [0]:
test_data.shape

In [0]:
prediction = model.predict(test_data)

In [40]:
prediction

array([[0.0000000e+00, 9.5116527e-30, 1.1846804e-35, 1.0000000e+00,
        0.0000000e+00, 3.9348881e-19, 0.0000000e+00, 3.9886877e-35,
        5.8404606e-28, 3.2317191e-25]], dtype=float32)

Set axis=-1 means, extract largest indices in each row. Here we have only one row.

In [0]:
import numpy as np

In [0]:
y = np.argmax(prediction, axis=-1)

In [43]:
y

array([3])

In [44]:
train_labels[10]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

Code challenge 
https://medium.com/coinmonks/handwritten-digit-prediction-using-convolutional-neural-networks-in-tensorflow-with-keras-and-live-5ebddf46dc8

In [0]:
test_images.shape

In [0]:
test_data = test_images

In [0]:
predictions = model.predict(test_data)

In [0]:
final_pred = np.argmax(predictions, axis=-1)

In [0]:
final_pred.shape

In [0]:
from sklearn import metrics

In [0]:

matrix = metrics.confusion_matrix(test_labels.argmax(axis=1), final_pred)